### ISSUE TITLE
bazel: Main issue for tracking all Bazel efforts

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#11283]
Roadmap document: https://docs.google.com/document/d/1odyKzmp6AYE2GHlyICFBalWd0Ye13byrMIP0oCTtV_4/edit?usp=sharing

# Bazelification of AGW C / C++ Services
- Proposal: https://github.com/magma/magma/issues/8338
- [x] https://github.com/magma/magma/issues/9714
- [x] https://github.com/magma/magma/issues/10890

## Clean up (Needs owners!)
- [x] https://github.com/magma/magma/issues/8494
- [x] https://github.com/magma/magma/issues/8467
- [x] https://github.com/magma/magma/issues/8321
- [x] https://github.com/magma/magma/issues/8457
- [x] https://github.com/magma/magma/issues/8453
- [x] https://github.com/magma/magma/issues/5945
- [x] https://github.com/magma/magma/issues/8625
- [x] https://github.com/magma/magma/issues/8457

# Bazelification of AGW Python Services
- Proposal: https://github.com/magma/magma/issues/11293
- [x] https://github.com/magma/magma/issues/9878
- [x] Strategy for testing and coverage collection for Python: https://github.com/magma/magma/issues/11163
- [x] Import fix ups: https://github.com/magma/magma/issues/11357
- [x] https://github.com/magma/magma/issues/12519
- [x] https://github.com/magma/magma/issues/11724

# Bazelification of Golang Services (Not yet planned)
- [ ] Orc8r
- [ ] FeG
- [ ] CWAG
- [x] src/go (done by utilizing Gazelle)
- [x] https://github.com/magma/magma/issues/11727

# Bazelification of Dockerized AGW services (Not yet planned)

- [x] POC: https://github.com/magma/magma/pull/10452

# Bazel build for ARM services

- [x] https://github.com/magma/magma/issues/12532

# Build environment issues
- https://github.com/magma/magma/issues/11040
- [x] Consolidate build environments (bazel-base and devcontainer, for example) https://github.com/magma/magma/issues/10860

# Proposals
- https://github.com/magma/magma/issues/11439
- https://github.com/magma/magma/issues/11480
- https://github.com/magma/magma/issues/12531 (internal)

# Fixes during migration
- https://github.com/magma/magma/pull/11498
- https://github.com/magma/magma/issues/11730
- https://github.com/magma/magma/issues/11743

# Changes needed after switchover
- https://github.com/magma/magma/issues/12755
- https://github.com/magma/magma/issues/11959
- https://github.com/magma/magma/issues/13353
- https://github.com/magma/magma/issues/13401
- https://github.com/magma/magma/issues/13807
- https://github.com/magma/magma/issues/14265
