### ISSUE TITLE
[agw] S1AP test cases failures with ASAN and LSAN enabled for C/C++ code

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#11978]
### Your Environment

- **Version:** master
- **Affected Component:** AGW
- **Affected Subcomponent:** MME

### Describe the Issue

- Master issue to track all failures running entire S1AP integ test suite with ASAN+LSAN enabled, applying the changes from https://github.com/magma/magma/pull/11883

### Sub-tasks

- [x]  https://github.com/magma/magma/issues/11968
- [x]  https://github.com/magma/magma/issues/11970
- [x]  https://github.com/magma/magma/issues/11977 
- [x] https://github.com/magma/magma/issues/12019
- [x] https://github.com/magma/magma/issues/12021
- [x] https://github.com/magma/magma/issues/12030

**Comment by themarwhal** [comment]
Should we also track  https://github.com/magma/magma/issues/11968 with this issue?

**Comment by ardzoht** [comment]
Added it to the task, thanks Marie!
