### ISSUE TITLE
Old node version in use (v12) might hold security implications

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#12209]
### Describe the Issue

- ~Node JS was upgraded to version 12.22 in https://github.com/magma/magma/pull/12206.~
- Old Node JS is still in use in some Github Actions jobs.
- The current version as of March 2022 is version 17.
- Using an very old version may have security implications.

### Solution for the Issue

- Upgrade node js to the current version.

### Known obstacles

A upgrade skipping several major version will [likely run into incompatibilities](https://github.com/magma/magma/pull/12206#issuecomment-1073865299). Node packages will probably also need to be upgraded.

### Tasks

- [x] Go through all Github Actions tasks and look for the Node deprecation warning.
- [x] If you see the warning, try to solve it by updating the corresponding jobs. If there are no updates for a job available, we may try to use a different action.
  - [x] In particular, take a look at the Slack notification action.
- [ ] Prepare internal review.

**Comment by LKreutzer** [comment]
On a related note:
Several GitHub actions need to be updated once versions without Node,js 12 are available.

Actions report warnings like: `Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout`

See e.g. workflow run https://github.com/magma/magma/actions/runs/3221111195

**Comment by ajahl** [comment]
### CI Workflows

- [ ] PR Check DCO	
- [ ] Magma Analyze With CodeQL
- [ ] AGW Generate GCC Warnings & Errors
- [ ] CWAG Lint & Test Operator
- [ ] FeG Lint & Test
- [ ] Orc8r Lint & Test
- [ ] PR Generate Hello
- [ ] Orc8r Analyze With Fossa
- [ ] PR Check Codeowners
- [ ] Push Helm Charts to Artifactory
- [ ] Docs Build & Deploy
- [ ] Magma Check Helm Dependencies
- [ ] AGW Lint
- [ ] PR Generate Comment On Workflow Failure
- [ ] PR Generate Unit Test Results
- [ ] PR Check Title Or Commit Message
- [ ] CWAG Format & Test
- [ ] Docs Lint & Check Generated Files In Sync
- [ ] PR Generate Labels
- [ ] AGW Build & Format Python
- [ ] PR Lint Reviewdog                                   
- [ ] AGW Build & Test Experimental Go Code
- [x] AGW Build, Format & Test Bazel
- [ ] NMS Lint & Test
- [x] AGW Build & Test LTE Integration With Make Dev Build
- [ ] .github/workflows/amis-workflow.yml  ???
- [ ] CWAG Build & Test Integration 
- [ ] Magma Publish Artifacts 
- [ ] Magma Build & Publish
- [ ] Magma Build, Publish & Test Federated Integration

**Comment by ajahl** [comment]
## Unmaintained Github Actions
tim-actions/get-pr-commits             
tim-actions/dco
mmagician/get-changed-files
electronjoe/gcc-problem-matcher
autero1/action-gotestsum
Ilshidur/action-slack

**Comment by ajahl** [comment]
A follow-up issue #14558 addresses the unmaintained Github actions that could not upgraded or replaced by alternative actions.
