### ISSUE TITLE
Upgrade Github runners to macOS 12 due to deprecation of macOS 10.15

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#13337]
### Subtasks

- [x] Change runners on to the new macos version
- [x] Fix pyenv command and make sure traffic server runs on ubunu-20.04
- [x] Run action on private fork to make sure actions still work with macOS 12

### Describe the Issue

The Github runners with macOS 10.15 are being deprecated soon enough. This will lead to lower availability and in the consequence to longer waiting times for job execution.

#### Tests
LTE integ test run: https://github.com/crasu/magma/runs/7555541971?check_suite_focus=true
CWF integ test run: https://github.com/crasu/magma/runs/7559855082?check_suite_focus=true
FEG integ test run: https://github.com/crasu/magma/actions/runs/2752365494

#### Suggested Resolution

Upgrade any macOS runners in CI to version **12**.

#### Target date

The deprecation date is give as **2022-08-30**!

#### Additional context

- Find additional information and details about the deprecation at
https://github.com/actions/virtual-environments/issues/5583
- Find an example usage of macOS 10.15 runners at https://github.com/magma/magma/blob/master/.github/workflows/lte-integ-test.yml#L19.
- There will be several "brown-out" periods. You will see the following errors during that times with all runs failing on those runners.
![grafik](https://user-images.githubusercontent.com/13189449/180230597-23868810-d1e0-4220-8b67-e19893941958.png)

**Comment by LKreutzer** [comment]
Cf. https://github.com/actions/virtual-environments/issues/5583

**Comment by nstng** [comment]
note: #13385 only bumps one workflow - cwf, fed, lte (make and bazel) are still open.

**Comment by LKreutzer** [comment]
I am currently testing if the pyenv setup, which is one of the issues blocking the upgrade to `macos-12`, can be removed.

Results TBD...

| Workflow  | Status  |
|---|---|
| LTE Make  |   |
| LTE Bazel  |   |
| FEG   |   |
| CWF  |   |
