### ISSUE TITLE
magma.deb is bazelified

### ISSUE THREAD

**Issue by nstng** [magma/magma#13416]
Problem during bazelification
- [x] scripts should be bazelified separately in order to split complexity - #13415
- on bazel base and the magma vm different folly versions are setup - this makes sessiond builds (and thus debian builds) not interchangeable 
  - [x] folly build needs to be fixed to run on bazel base (no sudo) and a new version is uploaded to focal-ci #13741
  - [ ] bazel base uses the new folly build during docker build [edit] ~~#13743~~ reverted, needs a better release strategy, see #13755
