### ISSUE TITLE
Upgrade Python dependencies after python 3.8 update

### ISSUE THREAD

**Issue by crasu** [magma/magma#13426]
## Subtasks

- [x] Try the branch from sebastians pr https://github.com/magma/magma/pull/12972
- [x] Test prod package creation locally by setting up a magma vm. Building the python packages (ask nils for the command).  Create magma debian package. Install magma debian package and dependencies.
- [ ] Inform 5G test folks that magma debian packages have been touched
- [x] Run integration tests with updated dependencies (lte/s1ap)
- [ ] Make sure that build all job runs for two consecutive runs on master

## Description

Many Python dependencies have not been updated in a while. But now that we have Python 3.8 everywhere a lot of these upgrades could be made.

An attempt was made here:

https://github.com/magma/magma/pull/12972

There are multiple steps necessary that make this a little complicated:

- Increase versions in setup.py files (as in the PR above). As a first step, try to avoid incompatible upgrades that make significant code changes necessary. There are a lot of low-hanging fruits, i.e. upgrades that just work.
- Also increase versions in requirements.in to make bazel happy (possibly need to generate requirements.txt afterwards?)
- Test that things still work. Unit, sudo and integration tests of VM.
- Create a new production release with the new versions. Make sure the production versions are also upgraded (depends on the whims of pydep).
- Test the new production release can actually be installed and works correctly. Use the new production VM integration test tool from https://github.com/magma/magma/issues/13263.
 

Hint: Lucas Gonze was also looking into some of these upgrades, so at least some of our existing versions have security issues.
https://github.com/magma/magma/pull/13222

**Comment by MoritzThomasHuebner** [comment]
Status update from my end:

I checked out @sebathomas 's branch and rebased it on master, which involved some manual merge conflict resolution. The dependencies appear to be fine for the most part, except that we need to change the version of `charset-normalizer` from 2.1.0 to 2.0.0 because of `requests` 2.28.0. There are also number of minor version upgrades that are possible and should be easy.

I found that the `pipdeptree` package is useful for analyzing dependencies. For this, activate the python build environment on the `magma_test` VM.
```
. $(PYTHON_BUILD)/env/activate
pipdeptree --reverse
```
This command also outputs conflicting requirements at the top. I am currently trying to figure out which versions can be safely upgraded.

It also appears that some requirements are not actually used at all? For example `jsonpointer` is only a direct dependency of the AGW and the orc8r. However, grepping for `jsonpointer` in magma only returns the entries in the `setup.py` files. Perhaps there is some obscured way in which it is used? Otherwise, it might have been thrown out of the production code at some point in the past.
```
pipdeptree --reverse --package jsonpointer
> jsonpointer==2.3
>  - lte==0.0.0 [requires: jsonpointer>=2.3]
>  - orc8r==0.0.0 [requires: jsonpointer>=2.3]
```

**Comment by MoritzThomasHuebner** [comment]
Status update today from me and @wolfseb:

`fpm` issues:
- We realized that `fpm` was using `easy_install` internally instead of `pip` to build dependencies. This behavior has changed in `fpm==1.14.0` but the dev VM runs on `1.12.0`. 
- `easy_install` has been deprecated since 2019 and is may now actually be causing issues.
- We can manually enforce `fpm` to use `pip`: `--python-pip /home/vagrant/build/python/bin/pip`

`pydep` issues:
- Currently, we do not build a docker debian package (and perhaps some other packages) because it is already installed before `pydep` runs. This issue can be easily fixed, but it is not clear if we are not breaking something else by doing so.

Dependencies we can't build right now:
- `cryptography==37.0.4`  -> Unsure of the cause, we cannot build other versions either
- `pyparsing==3.0.9` -> Missing `setup.py` might explain this
- `jsonschema==4.9.0` -> ?
- `pyroute2==0.7.2` -> ?

We may have to try some different versions until we find one that works for each of these dependencies...

All other dependencies are being built by `pydep` now!

Long term: Perhaps upgrade `fpm` and `pip`?

To-do:
- Fix `fpm` issues
- Fix `pydep` issues
- Run integ tests once all changes have been made
- check in updated lockfile?

**Comment by MoritzThomasHuebner** [comment]
As per suggestion , we might also not upgrade versions that we cannot build if the upgrade is not urgent.
