### ISSUE TITLE
Create and use a fork of aioeventlet

### ISSUE THREAD

**Issue by crasu** [magma/magma#13425]
**Subtasks**

- [x] Set up Magma fork of aioeventlet
- [x] Commit patches, readme and notice information to new repository
- [x] Create PR 
- [x] Merge it
- [x] Prepare internal review meeting

**Description:**

Instead of patching the existing library, which will not be possible for Python > 3.8, we want to publish a Magma fork that already contains the changes. Finish the fork in:
https://github.com/sebathomas/deb-python-aioeventlet/

Use the fork everywhere in Magma. Remove the patch from the Magma repo because it is already contained in the fork. Proof of concept for that:
https://github.com/magma/magma/pull/13044

**Comment by maxhbr** [comment]
Hey @jwagantall or @fabiopalumbo, 

can you create a fork of https://github.com/openstack-archive/deb-python-aioeventlet to https://github.com/magma/deb-python-aioeventlet/. Write permissions should be given to @magma/approvers-agw-pipelined. This was discussed and approved in https://wiki.magmacore.org/display/HOME/June+27%2C+2022+Meeting.

Once the fork it there we will
* fix the description
* fix the readme
* apply magma patches to aioeventlet
* apply https://github.com/magma/magma/pull/13044 to pull from fork instead of ad-hoc patching.

**Comment by Neudrino** [comment]
Should @magma/approvers-ci also work on that repository to add automation to build and push artifacts?

**Comment by ajahl** [comment]
PR: https://github.com/magma/magma/pull/13044
