### ISSUE TITLE
Replace Scapy

### ISSUE THREAD

**Issue by crasu** [magma/magma#13433]
## Possibly
- https://dpkt.readthedocs.io/en/latest/ 
- see also https://stackoverflow.com/questions/30826123/python-scapy-vs-dpkt

## Subtasks
- [ ] Extract dhcp client from mobilityd into a separate CLI application 5
- [ ] Remove scapy usage from pipelined 5
- [ ] Clean up Python environment setup so that scapy is not distributed any more (tests, new DHCP CLI tool)
- [ ] Prepare internal review meeting

## References
https://jira.tngtech.com/browse/FM-785

**Comment by wolfseb** [comment]
Done by #14297, #14418, and #14459.
