### ISSUE TITLE
Identify the external dependencies which MUST be system installed

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#13476]
## Tasks

- [x] Try to follow the documentation to set up the containerized AGW on a plain Ubuntu VM (see the agw_install_docker script below).
- [x] Document the necessary provisioning steps.
  - What needs to be installed on the host?
  - Try to find out why it is needed.
  - Is it really needed or can you just leave it out?
- [x] Prepare internal review meeting.

## Context

Magma currently has external dependencies, which are system installed. Some of those dependencies _must_ be installed on the host machine running Magma. Those dependencies might pose obstacles during containerization.

E.g. Kernel modules must usually be installed on the host machine. E.g. OVS?

At the moment, starting the docker containers requires a `make run`. Find out why this is needed. Which of the steps / results of `make run` are actually required.

## Acceptance Criteria

- Find external dependencies currently provisioned on the host machines
- Identify, which ones _must_ to be installed on the host machine
- The minimal set shall be identified
- For any found dependency, document,
  - if it needs to be installed on the host
  - why it does or does not
  - where it was found
  - if it is still actively maintained

## Additional information

- https://github.com/magma/magma/blob/a6cd59e068fd4db3ab79036dac3e0137993162b1/lte/gateway/deploy/agw_install_docker.sh#L114-L119
