### ISSUE TITLE
Add AMF configuration to gateway settings

### ISSUE THREAD

**Issue by thmsschmitt** [magma/magma#13505]
Add an AMF section to the LTE gateway config and an AMF tab to the "Gateway Edit" dialog.
See https://docs.magmacore.org/docs/next/lte/integrated_5g_sa#additional-amf-specific-configurations

![Image](https://user-images.githubusercontent.com/102796295/182859098-c6241b43-0bda-41a7-8d3a-b779e2983a31.png)

![Image](https://user-images.githubusercontent.com/102796295/182859569-f04bafb5-85c4-472a-9fcb-ee533ce8c63c.png)

## Tasks

- [x] Add a new AMF panel to the gateway configuration. Use the GET endpoint from the documentation to get the values.
- [x] Make it possible to configure the values. Add an "Edit" button and a pop-up window that calls the PUT endpoint to persist the configuration, similar to the other configuration options for a gateway.
- [x] E2E test that the values in the NMS are persisted in the AGW correctly. See the gateway.mconfig file.
- [x] Prepare internal review meeting.

**Comment by panyogesh** [comment]
@crasu : I guess that should be fine.

**Comment by panyogesh** [comment]
@crasu: All good, had a discussion with team. Please proceed with the changes.
