### ISSUE TITLE
Fix CWAG TestGyCreditExhaustionRedirect as it is responsible for about 50% of all cwag integ test failures

### ISSUE THREAD

**Issue by crasu** [magma/magma#13838]
## Summary

Currently TestGyCreditExhaustionRedirect fails about 10-20% of all cwag runs. This is responsible for making the CWAG integ tests run very frequently

# Tasks
* [ ] Reproduce failed test locally - see https://docs.magmacore.org/docs/next/cwf/dev_testing#run-integration-tests
* [ ] Understand and fix the timeouts
* [ ] Prepare internal review meeting

 ## Example run
https://storage.googleapis.com/magma-ci.appspot.com/cwf_integ_test_a94f1efd61ffb4de31fa05c140b4a6e471d5e1c7.html
