### ISSUE TITLE
Move or copy necessary release scripts into Magma repository

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#13883]
## Tasks
- [ ] Figure out if secrets can be provided securely to Github Action runs. This should be used to give a private artifactory access token to the jobs.
- [ ] Integrate docker promotion script into main magma repo. (Check out if a non-working version is already there?)
- [ ] Integrate helm promotion script into main magma repo. (Check out if a non-working version is already there?)
- [ ] Prepare internal review meeting.

## Acceptance criteria
- Make it possible to promote helm charts and docker containers from within in the magma repo via github action work flows
- Checkin the missing scripts from @ShubhamTatvamasi repo into the main magma repo
- Add required secrets to github actions or as input parameters

## Open Questions:
- Who should be allowed to trigger this workflow?
  - Idea: Use private token as input secret for workflow. -> Only people with access to Artifactory are allowed to use it.

## Implementation details
- Use own deploy repo if we cannot restrict who can execute the action
- Add a variable that defines the artifactory domain in only location in the script, in order to make it possible to migrate to another artifactory.

## Reference:
https://github.com/ShubhamTatvamasi/magma-artifactory-docker-promote
https://github.com/nstng/magma-artifactory-helm-promote
