### ISSUE TITLE
Make containerized AGW integ job pickup the correct containers

### ISSUE THREAD

**Issue by crasu** [magma/magma#14052]
# Background:

Currently the containerized AGW integ job always picks up the *:LATEST image. This will lead to race conditions between builds and  makes it impossible(?) to tests containers build by a pr branch.

# Acceptance criteria
* No more race conditions between build jobs
* Make it possible to pick up a pr version for integ tests
* Configure the workflow to run on master and release branches

# Implementation details
* Containers are currently pushed as follows
   * For prs the use the pr number and are pushed [here](https://artifactory.magmacore.org/ui/repos/tree/General/agw-ci%2Fagw_gateway_c)
   * For master build the containers are pushed to to [agw-test](https://artifactory.magmacore.org/ui/repos/tree/General/agw-test%2Fagw_gateway_c)
   * For the release branch there is just one tag which is overwritten with every [build](https://artifactory.magmacore.org/ui/repos/tree/General/agw-test%2Fagw_gateway_c%2F1.8)
   * We can either use the existing scheme to pickup containers or additonally always tag with the commit hash and then use the commit hash to pickup the correct version
   * Using the commit hash everywhere would have the advantage that after this change we no longer would have a single tag on the release branch

# Tasks
* [ ] For automatic runs, get the corresponding containers
  * from agw-test and use the latest commit hash for branch *master*
  * from agw-test and use the release tag for release branches
* [ ] For manual runs, make it possible to configure either a commit hash (-> agw-test) or a PR number (-> agw-ci).
* [ ] Configure the workflow to run on master and release branches
* [ ] Prepare internal review
