### ISSUE TITLE
[CI-Maintenance]: Task Tracker 

### ISSUE THREAD

**Issue by arora-sagar** [magma/magma#14099]
This issue contains link to multiple sub-issues which concerns CI-Run failure or flakiness, 

- [X]  Add 4G Federation test column in magma CI-Dashboard
- [ ] [LTE Integration test flakiness](https://github.com/magma/magma/issues/13954 )
- [ ] [Enable S1AP testing for Arm based AGW](https://github.com/magma/magma/issues/14102)
- [ ] Add 5G NGAP Tester test column in magma CI-Dashboard

**Comment by shahrahman-fb** [comment]
Closing this issue as part of a repository cleanup effort. This issue has had no activity for over 2 years.

If this issue is still relevant, please reopen it or file a new issue with updated information. We are actively maintaining the project again and want to focus on current, actionable issues.

See: #15833 (Phase 1 cleanup), #15828 (tracking issue)
