### ISSUE TITLE
Extract mobilityd DHCP client into a separate application

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#14297]
## Acceptance Criteria
* Extract the mobilityd DHCP client code into a separate application (no longer in the mobilityd folder and no longer imported there). Note that there already is a script mobility_dhcp_cli.py that provides a CLI interface for this client.
* Replace all usages of DHCP within mobilityd with shell calls that run the extracted DHCP client application.

## Tasks
* [x] Set up a test setup locally that runs mobilityd in DHCP allocation mode (https://docs.magmacore.org/docs/howtos/config_agw_bridged#dhcp)
  * Set up dnsmasq as DHCP server (or choose another one).
  * Configure mobilityd to do DHCP.
  * Trigger an attach to have mobilityd do DHCP requests. Idea: Use test_attach_detach.
* [x] Move the renewal logic out of DHCP client into its own class or the DHCP allocator.
* [x] Rip out the DHCP client from mobilityd into an external application. It needs to have two functions:
  * Get lease
    * Input: mac address
    * Output: lease (IP) and renewal timestamp
  * Renew lease
    * Input: old mac and IP
    * Output: renewal timestamp
* [x] Call the new external application in in the DHCP allocator.
* [x] Think about async handling of the extracted application.
* [x] Test the new flow with the setup from step 1.
* [x] Prepare internal review meeting.
