### ISSUE TITLE
AGW integ tests using the traffic server fail randomly due to overlapping dev vm ips

### ISSUE THREAD

**Issue by crasu** [magma/magma#14312]
### Your Environment

- Virtual box dev vm
- Seems to happen in feg/cwag and agw (only analyzed the issue in agw)

### Describe the Issue

- Integration tests involving the traffic server some times fail because the traffic server cannot connect to the test vm
- After several restarts of the dev vm/traffic server the test starts to work and will from that point on always work
- The reason for that seems to be a overlapping gateway ip of the dev vm with the hostonly ip of the host system (192.168.129.1)

### How to reproduce

- Run test_attach_detach_attach_dl_tcp_data.py data
- If it works restart the traffic server 1-3 times until there is a connection timeout
- After the restart the connection from traffic server to the test vm should timeout and you should not be able to ping the ue ip from the traffic server

#### How to resolve
- Migrate to virtualbox internal networks between trfserver <-> dev vm  <-> test vm ([see](https://www.virtualbox.org/manual/ch06.html#network_internal))
- Change the ip of the dev vm or virtualbox to a different one

### Tasks
- [x] Replace the Vagrantfile interface config. Make it "internal network".
- [x] Run traffic-server integration tests while repeatedly restarting the traffic server (between tests) to check if they're still flaky. Don't forget to `disable-tcp-checksumming` on all three VMs. If the tests are still flaky, you may try changing the IP 192.168.129.1 to something else (search the entire codebase).
- [x] Prepare internal review meeting.
