### ISSUE TITLE
Enable unit tests for radius in the CI

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#14350]
## Summary

The task #14291 and tests in #14347 showed that the radius tests are not executed in the CI. We should add CI jobs for them (or extend existing jobs).

## Acceptance criteria

* The radius unit tests in `feg/radius/src` and `feg/radius/lib` are run in the CI (the lib tests might already be in the CI). Think about running linters too.
* The new CI jobs are green.

## Tasks

- [x] Enable the tests in the CI. You can take a look at `make -C ${MAGMA_ROOT}/feg/gateway precommit` how to run Go tests.
- [x] Enable linting for the code if there is no linter yet.
- [x] Make sure everything is green. If tests are red try to fix them, but don't invest unlimited effort. You can ignore/skip tests if necessary and create a follow-up task.
- [x] Prepare internal review meeting.
