### ISSUE TITLE
Create separate release for the new DHCP CLI tool

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#14459]
## Acceptance criteria

* The new DHCP CLI tool is released in a separate Debian package by the Bazel build job.
* The code of the tool is not included in the main Magma package created by Bazel.
* The package is uploaded to focal-ci artifactory next to the old packages.
* The new package is installed in all relevant CI jobs that install Magma.

## Tasks

* [x] Build the script with Bazel.
  * Put it into a separate folder inside lte/gateway.
  * The script may still import code from Magma, but not the other way around.
  * Tests are run within the Magma VM virtualenv, same as other Python unit tests.
* [x] Build the Debian package for the new script. You can pair with Nils.
* [x] Publish the package.
* [x] Make Magma main Debian package depend on the new package.
* [x] Check CI jobs that install Magma to make sure they also install the new package.
* [x] Prepare sprint review.

**Comment by MoritzThomasHuebner** [comment]
Closing this issue. I have removed any follow up tasks to https://github.com/magma/magma/issues/14740
