### ISSUE TITLE
Artifactory Switch - MagmaCore to LinuxFondation

### ISSUE THREAD

**Issue by nstng** [magma/magma#14495]
This issue describes the switch from the magma core (MC) artifactory to the linux foundation (LF) artifactory.

#### Background

At 2022.12 the license for the MC artifactory ends. Starting then an artifactory hosted by the LF will be used.

#### Requirements for the LF artifactory

* The community will not get credentials for the LF artifactory, this is, manual manipulations (add, edit, delete) will not be possible. All actions must happen via CI by credentials provided as git hub (GH) secrets.
* In problematic situations the LF support can do manual changes to the artifactory.
* For technical reasons the repositories need to be renamed (e.g., `debian-test` -> `magma-packages-test`). This implies that no redirect from the MC URL to the LF URL will be possible.

#### Migration Plan

* all artifacts in the MC artifactory are synced to the LF artifactory
* while the MC artifactory is still usable, all existing MC workflows are doing a double push to both artifactories
  * `build_all.yml`, `bazel.yml`
* all currently manual workflows for uploading artifacts in MC are implemented for CI
  * `3rd-party.yml`, `ovs`
* as soon as possible ...
  * the push to the MC artifactory is removed
  * in master all references to the MC artifactory are changed to the LF artifactory
  * in release branches the MC artifactory is changes to the LF artifactory

#### Issues

01 High Prio
06 Middle Prio
11 Low Prio

##### Initial Sync

* [x] 01 #13897
  * this only mentions `*-prod` repos - `*-test` should also be affected

##### Double Push

* [x] 01 #14445
* [x] 01 #13898
* [x] 11 3rd party #14545 - no double push, just switch to new artifactory
* [x] 01 .github/workflows/agw-build-publish-container.yml
  * First part: #14534
  * Push to new artifactory.
* [x] 01 .github/workflows/deploy-build-from-pr.yml -> remove instead: #14507 
* [ ] 11 adapt bazel.yml and build_all.yml for v1.8 and maybe v1.7 #14624

##### Add Missing Workflows

* [x] 06 #13431
* [x] 06 #14365
* [x] 11 ovs #14572
* [x] 11 all release promote workflows #14590
  * .github/workflows/docker-promote.yml
  * .github/workflows/helm-promote.yml
* [x] 11 #14529
* [ ] 11 drop hello world workflow and get related packages deleted #14616

##### Testing

* [x] 01 #14272

##### Switch

* [x] 06 change all endpoints on master #14508
* [x] 06 change all endpoints on v1.7 and v1.8 #14581
* [x] 11 follow-up: check in GPG key instead of downloading from server #14570
* [x] 06 #14531
* [x] 06 Prepare notification of users to change sources.list

##### Ad Hoc Problems

* [x] 01 #14500
  * [x] Workaround: [push dummy packages everywhere ](https://github.com/magma/magma/actions/workflows/magma-push-dummy-package.yml)
* [x] 01Docker URL issue
* [x] 01 LF artifactory clean-up - remove not needed repositories
* [x] 01 #14497
* [x] 01 #14505 
* [x] 01 use latest tag for ghz images #14594

##### Open
* [x] 01 artifactory is used in pre-burn VM images #14514
  * [ ] 11 follow-up: create new base images with new artifactory baked in #14541
* [x] 01 build_all is flaky - size notification, idna issue
* [ ] 06 remove unused folders from artifactory https://magmacore.slack.com/archives/C03TN1LM8CB/p1670320477210849

##### Unsorted Issues

* [x] #14453
* [x] #13450
* [x] #13439

#### External Resources

* https://wiki.magmacore.org/display/HOME/2022-11-18+Artifactory+Status+Meeting
* Main discussion happens in Slack #questions-to-linux-foundation-it

**Comment by shahrahman-fb** [comment]
Closing this issue as part of a repository cleanup effort. This issue has had no activity for over 2 years.

If this issue is still relevant, please reopen it or file a new issue with updated information. We are actively maintaining the project again and want to focus on current, actionable issues.

See: #15833 (Phase 1 cleanup), #15828 (tracking issue)
