### ISSUE TITLE
Follow up issue for remaining tasks on the new DHCP CLI tool

### ISSUE THREAD

**Issue by MoritzThomasHuebner** [magma/magma#14740]
### Acceptance criteria

- [ ] Add scaling tests for DHCP ip allocation mode ~#14724~ #14887
- [x] Use json file to communicate with the DHCP helper cli #14731
- [x] Add missing type hints #14732
- [x]  Improve dhcp_helper_cli.py help #14739
