### ISSUE TITLE
Fabric is Cleaned-Up

### ISSUE THREAD

**Issue by nstng** [magma/magma#14909]
This a collection of technical debt in fabric files. This was identified during #14612 and should be handled after the respective PR is merged.

- [x] `get_test_summaries` function and calls should be refactored. Havin a host argument seems to be unused. Arguments `integ_tests` and `sudo_tests` should be generalized (maybe call function twice) #14998
- [ ] cleanup boiler plate code in `/lte/gateway/fabfile.py` (setup for containerized, deb, dev integ tests and federated integ tests) #15027
- [x] remove unused functions and tasks from fabfiles
- [x] improve handling of `exit()`/`sys.exit()`, and `raise` calls in fabric files #15020 
- [x] adapt more pythonic syntax as described in review comment https://github.com/magma/magma/pull/14806#pullrequestreview-1294884555 #15002
- [x] Some minor refactoring, including formatting changes. ~#15004~ (reverted in #15030 ), #15035
