### ISSUE TITLE
Collection of tickets regarding current CI state

### ISSUE THREAD

**Issue by maxhbr** [magma/magma#15222]
(This issue was created 2023-06-20 and will be out of sync soon.)

# background:
* https://magmacore.slack.com/archives/C01Q1T14YJ2/p1686905954161159
* https://magmacore.slack.com/archives/C01MDUQDFC3/p1686915921379039
* https://magmacore.slack.com/archives/C01MDUQDFC3/p1687198180093079

# open points (overview):

- [x] https://github.com/magma/magma/issues/15161 : not linking Debian artifacts on dashboard since they were moved to bazel job
  - [x] invalid value workflow reference: cannot specify version when calling local workflows
Artifactory now starts failing. Probably also due to missing credentials.
- [x] https://github.com/magma/magma/issues/15159: firebase script should accept AGW artifacts
- [x] https://github.com/magma/magma/issues/15223: the publish to firebase script fails with an syntax error

infrastructure issues:
- [x] the job now sucessfully calls the bazel job, but that fails due to missing credentials (`message: Secret SLACK_WEBHOOK is missing. Please add it to this action for proper execution`.)
- [x] https://github.com/magma/magma/issues/15227 the publish debian packages step, that uploads artifact to LF
- [x] https://github.com/magma/magma/issues/15220 

Failing tests
- [ ] feg integ tests are failing
- [ ] sudo python tests are failing
- [ ] ...

# open points (details):
### was tried to fix with https://github.com/magma/magma/pull/15214
since then it has the following issues:
#### invalid value workflow reference: cannot specify version when calling local workflows
fixed by: https://github.com/magma/magma/pull/15219 :heavy_check_mark: 
#### the job now sucessfully calls the bazel job, but that fails due to missing credentials (`message: Secret SLACK_WEBHOOK is missing. Please add it to this action for proper execution`.):
see: https://github.com/magma/magma/pull/15221
## https://github.com/magma/magma/issues/15159: firebase script should accept AGW artifacts
potenital fix: https://github.com/magma/magma/pull/15226
## https://github.com/magma/magma/issues/15223:  the publish to firebase script fails with an syntax error
potential fix: https://github.com/magma/magma/pull/15224
## https://github.com/magma/magma/issues/15220

**Comment by maxhbr** [comment]
CC @panyogesh , @moyilakhila , @tapasmishra

**Comment by tapasmishra** [comment]
@maxhbr  Please mark this issue as closed by marking all the task completed.

**Comment by panyogesh** [comment]
Closing the ticket as per last comment.
