### ISSUE TITLE
bounty: add rate limiting in nms routes

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#15348]
# problem

Some of the routes in nms perform expensive operations such as accessing the file system, executing an operating system command or interacting with a database without limiting the rate at which requests are accepted. 

# solution

A Typescript engineer should come up with a general solution for rate limiting, then apply it to each of the work items below. There may already be code for rate limiting that simply needs to be added to these contexts.

# work items

- [ ] nms/.../auth/express.ts:199
- [ ] nms/server/auth/express.ts:178
- [ ] nms/server/auth/express.ts:178
- [ ] nms/server/auth/express.ts:110
- [ ] nms/server/auth/expressOnboarding.ts:54

# project management

https://github.com/magma/magma/issues/15348

# bounty

The TSC should consider funding the work. Proposed amount: $1500.

Acceptance criteria: rate limiting has been implemented and merged, with unit tests, for all of the above cases.

**Comment by lucasgonze** [comment]
Passed TSC vote on December 11, 2023. Ready for promotion.

**Comment by lucasgonze** [comment]
Announced in #general.

**Comment by lucasgonze** [comment]
No bids. $1500 is probably not enough. What is the right amount? If we pay a high enough price to get it done, will the budget be adequate?

**Comment by lucasgonze** [comment]
@tmdzk says:
> my friend has the rate limiter middleware up and running, he's currently writing tests. do we want to include that to 1.9?

**Comment by lucasgonze** [comment]
I have reviewed the PR https://github.com/magma/magma/pull/15380 and am satisfied it addresses all requirements here.

**Comment by lucasgonze** [comment]
The TSC votes on acceptance 4/22 and authorized Linux Foundation to make payment.

**Comment by lucasgonze** [comment]
Payment has been made and has gone through. 

Victory!
