### ISSUE TITLE
Proposal: Governance Reset

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#15390]
# Proposal: Governance Reset

This ticket obsoletes and updates https://github.com/magma/magma/issues/15376

## Problem

Magma governance is mainly obsolete cruft. It was originally structured to fit a Meta-centric orientation. In the shift to independence and a proper open source community the governance has not kept up.

## Solution

Revisit every aspect of governance:

- [x] Rewrite charter
- [x] Rewrite all github.com/magma/community documents and community-related documents in the magma repository.
- [x] Proposed new structure for the TSC, including quorum changes
- [x] Ensure compliance with legal constraints
- [x] Shepherd votes by current TSC to put changes into practice
- [x] Build consensus and buy-in to the greatest extent possible

## Non-goals

Changes to the formal non-profit. However I will probably have to research and document what the non-profit is.

Advocacy. Though I will and do have personal points of view, they are out of scope in this proposal. 

### Timeout

Proposed timeout on membership:

    Three months without any participation in any way
    Three TSC votes without participation

When a member departs, a call for an election to fill their seat will be made.

Address questions:

    How long can the seat be vacant?
    If a TSC member is on timeout - can (s)he be reinstated?
    What happens to the quorum rules when a TSC membership is cancelled and there are less than 5 members?

### Formalize Participation and Non-Participation

We need to define the participation in a vote properly. Not participating in a vote as a form of statement (ex. the member is so agains something so he dosn't want to vote in order not to contribute to that motion at all) is a valid way to express disagreement. This form of not participating should not lead you to disqualification from TSC, therefore maybe we should consider if there was activity not only formal vote. Also, we need to make sure we give enough time for the TSC member to be active on the vote, so just saying not participating in three votes without adding a perspective of a timeline can lead to automatic disqualifications. Ex: we call for 3 votes in a single day and all 3 are voted (pass of fail), the people who had not voted are on this issues will be automatically subject of the rule of not participating in 3 votes since there is no time frame.

Proposal: add abstention (or "present") to vote options.

    Abstention preserves TSC seat.
    Abstention doesn't count in quorum.

Quorum rules determined by number of voters on last vote.

Snap elections need to be accounted for.

Add "not participating in three votes AND not voting for three weeks" to timeout rules.

Add guiding principles about fairness to community and also fairness to the voter in the power to express themselves. Create a text preamble.

### New plurality approach

A sensible way to have a flexible quorum of 3-5 members

This ticket absorbs and moots https://github.com/magma/magma/issues/15375

## Tasks

Professional writing for the new documentation.

Eliminate out of date documentation that would contradict new structures.

Talk to Legal at Linux Foundation.

Coordinate with Board of Directors for non-profit

Initiate a vote under the old roles to accept the new rules

## Operational Issues

I am requesting $4,000 to execute this proposal.

Note that I am making this proposal as an independent and not under the OSPOCO banner.

**Comment by jordanvrtanoski** [comment]
I second this proposal

**Comment by lucasgonze** [comment]
Motion to vote: Lucas.
Seconded: Jordan.
Next: call for vote.

**Comment by jordanvrtanoski** [comment]
Vote: +1

**Comment by lucasgonze** [comment]
See https://github.com/orgs/magma/projects/25/views/1

**Comment by panyogesh** [comment]
+1

**Comment by lucasgonze** [comment]
Sandra met with LF Legal. They said:

1. The canonical version of the Charter is https://github.com/magma/magma/blob/master/Magma_Technical_Charter_Final_1-26-2021.docx.pdf. No other version counts.
2. Our proposed changes do not contradict anything in the charter. There is enough ambiguity there to accommodate the proposed changes, but as additions rather than modifications.
3. The place to publish the new voting rules is the CONTRIBUTING file

In today's TSC call we resolved to follow that path. Lucas is assigned to move the edits from a modified charter to a modified CONTRIBUTING. We will then vote on acceptance of that file.

**Comment by lucasgonze** [comment]
Draft pull request https://github.com/magma/magma/pull/15438

**Comment by lucasgonze** [comment]
Motion for acceptance: Lucas Gonze
Seconded by: TBD

**Comment by jblakley** [comment]
I vote yes.

**Comment by panyogesh** [comment]
+1
