### ISSUE TITLE
[MME] Address any pertinent clang-tidy findings in MME

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5302]
## Opportunity

A new Magma Draft PR achieves:

- Dockerized build and test of MME (`cd /magma/lte/gateway/` and `make test_oai`)
- Clang build support / capability of same
- Clang-tidy analysis
- VS-Code Remote Container checkout (one-click build / VS code integration)

Early exploration is finding immediate clang-tidy findings of value (e.g. potential null pointer access, security findings, etc).

## Environment Setup

Follow the [Readme:Setup](https://github.com/electronjoe/magma/blob/experimental-vscode-dockerized/.devcontainer/README.md#setup) instructions of the Draft PR.  After completion you should have a VS Code managed container with this Draft PR checked out within - and ability to `make test_oai` from within `/lmagma/lte/gateway`.

## Using Clang-Tidy

See the [Readme:Using Clang Tidy](https://github.com/electronjoe/magma/blob/experimental-vscode-dockerized/.devcontainer/README.md#using-clang-tidy) for details on how to get Clang-Tidy warnings in VS Code.

## Fix your first Clang-Tidy issue

- Within VS Code, open [TLVDecoder.c Line 44](https://sourcegraph.com/github.com/magma/magma/-/blob/lte/gateway/c/oai/common/TLVDecoder.c?subtree=true#L44)
- Clang-Tidy should alert you to the detected null pointer dereference here
- Continue exploring this and other files for Clang-Tidy filings, fix and submit PRs
- Recall from [Readme:Using Clang Tidy](https://github.com/electronjoe/magma/blob/experimental-vscode-dockerized/.devcontainer/README.md#using-clang-tidy) you may need to update `clang-tidy.compilerArgs` (you can fix in-place in your docker but also please notify me - we will fixup this draft PR)
- Recall from [Readme:Fix Intellisense](https://github.com/electronjoe/magma/tree/experimental-vscode-dockerized/.devcontainer#fixing-intellisense) that there may be missing include directories for IntelliSense (you can fix in-place in your docker but also please notify me - we will fixup this Draft PR)

**Comment by electronjoe** [comment]
This GH Issue is labeled `Some clang tidy findings` because this GH issue is not intended to be insane =D But the below are to document the state of things until I get this into Continuous Integration (hopefully soon).

Here is a summary of the total findings of clang-tidy (with a subset of the checks turned on, I **omitted* formatting, readability, etc).  Analysis was run on Magma @ [6c13c49](https://github.com/magma/magma/commit/9cc4be1e362e4cd0171be2bfcb47a054d6c13c49).

```
root@ecee08edef4b:/build/c/oai# grep "\]" ~/Downloads/clang.findings.txt | grep warning: | awk -F'[][]' '{print $2}' | sort | uniq -c
   2 android-cloexec-fopen
   1 android-cloexec-open
  26 bugprone-branch-clone
   9 bugprone-macro-parentheses
 123 bugprone-narrowing-conversions
 186 bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp
   5 bugprone-signed-char-misuse,cert-str34-c
  17 bugprone-sizeof-expression
   8 bugprone-suspicious-string-compare
   9 bugprone-too-small-loop-variable
   4 bugprone-undefined-memory-manipulation
   3 cert-dcl16-c
   1 cert-env33-c
  55 cert-err34-c
  28 cert-err58-cpp
   1 cert-msc30-c,cert-msc50-cpp
   1 cert-msc32-c,cert-msc51-cpp
  31 clang-analyzer-core.CallAndMessage
  48 clang-analyzer-core.NullDereference
   4 clang-analyzer-core.uninitialized.Assign
  63 clang-analyzer-deadcode.DeadStores
   1 clang-analyzer-optin.cplusplus.VirtualCall
   1 clang-analyzer-optin.portability.UnixAPI
   1 clang-analyzer-security.insecureAPI.strcpy
   8 clang-analyzer-unix.Malloc
  10 clang-analyzer-unix.MallocSizeof
   5 misc-misplaced-const
   6 misc-no-recursion
   5 misc-redundant-expression
  12 misc-unused-using-decls
```

- [ ] clang-analyzer-core.CallAndMessage - Unassigned - #5345 
- [ ] clang-analyzier-core. NullDereference - @electronjoe in progress - #5334
- [ ] clang-analyzer-core.uninitialized.Assign - Unassigned - #5343 
- [ ] clang-analyzer-deadcode.DeadStores - Unassigned - #5364 
- [ ] clang-analyzer-unix.Malloc - anushadatar - #5333
- [ ] clang-analyzer-unix.MallocSizeof - PRs in Review - #5326 

Descriptions of each check can be found on the [Clang-Tidy Documentation](https://clang.llvm.org/extra/clang-tidy/checks/list.html).

Full logs from the above are available in [This](https://gist.github.com/electronjoe/987d20e3e730d0a22ce184644c70b449) Github Gist.

I will work on automating the output of this report to our CircleCI pipeline as metrics we can monitor.

**Comment by electronjoe** [comment]
I spoke with @anushadatar about picking off some of these / testing out the VS Code dev environment.

Maybe you pick off a class of these issues from above - and then go through them? We can break off a GH Issue for that sub-topic and make it clear what you are working on (and let others work on other findings)?
