### ISSUE TITLE
[MME] Address Clang-Tidy clang-analyzer-unix.MallocSizeof findings

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5326]
This GH Issue is to investigate the clang-analyzer-unix.MallocSizeof findings from Clang-Tidy. Analysis was run on Magma @ [6c13c49](https://github.com/magma/magma/commit/9cc4be1e362e4cd0171be2bfcb47a054d6c13c49).

This is a result of #5302 execution of Clang-Tidy.

To keep track of the findings and status of each, here is a checklist which will tie to PRs:

- [ ] hashtable.c:460 - PR #5327
- [ ] hashtable.c:493 - PR #5327
- [ ] hashtable_uint64.c:436 - PR #5328
- [ ] hashtable_uint64.c:466 - PR #5328
- [ ] grpc_service_task.c:73 - PR #5329
- [ ] nas_procedures.c:589 - PR #5330 - PR aborted WAI need Clang-TIdy Annotation
- [ ] nas_procedures.c:625 - PR #5330 - PR aborted WAI need Clang-TIdy Annotation
- [ ] nas_procedures.c:659 - PR #5330 - PR aborted WAI need Clang-TIdy Annotation
- [ ] nas_state_converter.cpp:1078 - PR #5332  - PR aborted WAI need Clang-TIdy Annotation
- [ ] nas_state_converter.cpp:1092 - PR #5332  - PR aborted WAI need Clang-TIdy Annotation

```
/magma/lte/gateway/c/oai/lib/hashtable/hashtable.c:460:14: warning: Result of 'calloc' is converted to a pointer of type 'hash_key_t', which is incompatible with sizeof operand type 'hash_key_t *' [clang-analyzer-unix.MallocSizeof]
  ka->keys = calloc(hashtblP->num_elements, sizeof(hash_key_t*));
             ^
/magma/lte/gateway/c/oai/lib/hashtable/hashtable.c:460:14: note: Result of 'calloc' is converted to a pointer of type 'hash_key_t', which is incompatible with sizeof operand type 'hash_key_t *'
```

```
/magma/lte/gateway/c/oai/lib/hashtable/hashtable.c:493:18: warning: Result of 'calloc' is converted to a pointer of type 'void *', which is incompatible with sizeof operand type 'hash_key_t *' [clang-analyzer-unix.MallocSizeof]
  ea->elements = calloc(hashtblP->num_elements, sizeof(hash_key_t*));
                 ^
/magma/lte/gateway/c/oai/lib/hashtable/hashtable.c:493:18: note: Result of 'calloc' is converted to a pointer of type 'void *', which is incompatible with sizeof operand type 'hash_key_t *'
```

```
/magma/lte/gateway/c/oai/lib/hashtable/hashtable_uint64.c:436:14: warning: Result of 'calloc' is converted to a pointer of type 'hash_key_t', which is incompatible with sizeof operand type 'hash_key_t *' [clang-analyzer-unix.MallocSizeof]
  ka->keys = calloc(hashtblP->num_elements, sizeof(hash_key_t*));
             ^
/magma/lte/gateway/c/oai/lib/hashtable/hashtable_uint64.c:436:14: note: Result of 'calloc' is converted to a pointer of type 'hash_key_t', which is incompatible with sizeof operand type 'hash_key_t *'
```

```
/magma/lte/gateway/c/oai/lib/hashtable/hashtable_uint64.c:466:18: warning: Result of 'calloc' is converted to a pointer of type 'uint64_t', which is incompatible with sizeof operand type 'uint64_t *' [clang-analyzer-unix.MallocSizeof]
  ea->elements = calloc(hashtblP->num_elements, sizeof(uint64_t*));
                 ^
/magma/lte/gateway/c/oai/lib/hashtable/hashtable_uint64.c:466:18: note: Result of 'calloc' is converted to a pointer of type 'uint64_t', which is incompatible with sizeof operand type 'uint64_t *'
```

```
/magma/lte/gateway/c/oai/tasks/grpc_service/grpc_service_task.c:73:41: warning: Result of 'calloc' is converted to a pointer of type 'grpc_service_data_t', which is incompatible with sizeof operand type 'grpc_service_data_t *' [clang-analyzer-unix.MallocSizeof]
  grpc_service_config                 = calloc(1, sizeof(grpc_service_config));
                                        ^
/magma/lte/gateway/c/oai/tasks/grpc_service/grpc_service_task.c:73:41: note: Result of 'calloc' is converted to a pointer of type 'grpc_service_data_t', which is incompatible with sizeof operand type 'grpc_service_data_t *'
/magma/lte/gateway/c/oai/tasks/grpc_service/grpc_service_task.c:73:51: warning: suspicious usage of 'sizeof(A*)'; pointer to aggregate [bugprone-sizeof-expression]
  grpc_service_config                 = calloc(1, sizeof(grpc_service_config));
```

```
/magma/lte/gateway/c/oai/tasks/nas/nas_procedures.c:589:7: warning: Result of 'calloc' is converted to a pointer of type 'nas_emm_specific_proc_t', which is incompatible with sizeof operand type 'nas_emm_attach_proc_t' [clang-analyzer-unix.MallocSizeof]
      calloc(1, sizeof(nas_emm_attach_proc_t));
      ^
/magma/lte/gateway/c/oai/tasks/nas/nas_procedures.c:589:7: note: Result of 'calloc' is converted to a pointer of type 'nas_emm_specific_proc_t', which is incompatible with sizeof operand type 'nas_emm_attach_proc_t'
```

```
/magma/lte/gateway/c/oai/tasks/nas/nas_procedures.c:625:7: warning: Result of 'calloc' is converted to a pointer of type 'nas_emm_specific_proc_t', which is incompatible with sizeof operand type 'nas_emm_tau_proc_t' [clang-analyzer-unix.MallocSizeof]
      calloc(1, sizeof(nas_emm_tau_proc_t));
      ^
/magma/lte/gateway/c/oai/tasks/nas/nas_procedures.c:625:7: note: Result of 'calloc' is converted to a pointer of type 'nas_emm_specific_proc_t', which is incompatible with sizeof operand type 'nas_emm_tau_proc_t'
```

```
/magma/lte/gateway/c/oai/tasks/nas/nas_procedures.c:659:7: warning: Result of 'calloc' is converted to a pointer of type 'nas_emm_con_mngt_proc_t', which is incompatible with sizeof operand type 'nas_sr_proc_t' [clang-analyzer-unix.MallocSizeof]
      calloc(1, sizeof(nas_sr_proc_t));
      ^
/magma/lte/gateway/c/oai/tasks/nas/nas_procedures.c:659:7: note: Result of 'calloc' is converted to a pointer of type 'nas_emm_con_mngt_proc_t', which is incompatible with sizeof operand type 'nas_sr_proc_t'
```

```
/magma/lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp:1078:38: warning: Result of 'calloc' is converted to a pointer of type 'nas_emm_specific_proc_t', which is incompatible with sizeof operand type 'nas_emm_attach_proc_t' [clang-analyzer-unix.MallocSizeof]
          (nas_emm_specific_proc_t*) calloc(1, sizeof(nas_emm_attach_proc_t));
                                     ^
/magma/lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp:1078:38: note: Result of 'calloc' is converted to a pointer of type 'nas_emm_specific_proc_t', which is incompatible with sizeof operand type 'nas_emm_attach_proc_t'
```

```
/magma/lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp:1092:38: warning: Result of 'calloc' is converted to a pointer of type 'nas_emm_specific_proc_t', which is incompatible with sizeof operand type 'nas_emm_detach_proc_t' [clang-analyzer-unix.MallocSizeof]
          (nas_emm_specific_proc_t*) calloc(1, sizeof(nas_emm_detach_proc_t));
                                     ^
/magma/lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp:1092:38: note: Result of 'calloc' is converted to a pointer of type 'nas_emm_specific_proc_t', which is incompatible with sizeof operand type 'nas_emm_detach_proc_t'
```
