### ISSUE TITLE
Bazel build POC for SessionD

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#8049]
Ongoing PR for reference: https://github.com/magma/magma/pull/7776

Timeline Doc: https://fb.quip.com/5FXiAbudeQfU

### Goals

* Get a prototype of Bazel configurations needed to build SessionD
* Get SessionD unit tests running
* Validate produced SessionD build by plugging it into S1ap tester

- [x] Build a clean Docker environment with bazel to iterate on Bazel changes in a reproducible manner (https://github.com/magma/magma/issues/8866)
- [x] Build all C++ proto dependencies (https://github.com/magma/magma/issues/8867)
- [x] Build `orc8r/gateway/c/common` and make it accessible from `lte/gateway/c/session_manager` (https://github.com/magma/magma/issues/8868)
- [x] Build external libraries (https://github.com/magma/magma/issues/8869)
    - [x] `cpp-redis`
    - [x] `yaml-cpp`
    - [x] `google-mock`
    - [x] `google-test`
    - [x] `nlohmann_json`
    - [x] `folly` - We may need to try both of the options below (~1 week)
        * building `folly` with Bazel directly as in [bazelment/trunk](https://github.com/bazelment/trunk)
        * using Cmake to build `folly` separately then linking into SessionD build
            * Analysis of whether we can replace folly (with stdlib or other) might be useful here
- [x] Build the rest of SessionD! (~2-3 days) (https://github.com/magma/magma/issues/8870)
- [x] Test produced build (~2-3 days) (https://github.com/magma/magma/issues/8871)
- [x] Check for VM compatibility - getting Bazel to run inside our VM (https://github.com/magma/magma/issues/8872)
- [x] Check for Clion remote debugging compatibility (https://github.com/magma/magma/issues/8873)

## Follow up issues
- https://github.com/magma/magma/issues/8299
- https://github.com/magma/magma/issues/8644
- https://github.com/magma/magma/issues/8625
- https://github.com/magma/magma/issues/8577
- https://github.com/magma/magma/issues/8494
- https://github.com/magma/magma/issues/8467
- https://github.com/magma/magma/issues/8457
- https://github.com/magma/magma/issues/8453
- https://github.com/magma/magma/issues/8321

**Comment by uri200** [comment]
Can we please add to this `check CLON debugger works` so we don't lose that functionality?

**Comment by themarwhal** [comment]
> Can we please add to this `check CLON debugger works` so we don't lose that functionality? 

Yea can add that to the checklist! The item is already tracked in a spreadsheet somewhere :)

**Comment by themarwhal** [comment]
Moved all the remaining techdebt tasks to https://github.com/magma/magma/issues/11283
