### ISSUE TITLE
bazel: Bazelify MME

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#9714]
Issue tracking all blockers to migrate C/C++ for production: https://github.com/magma/magma/issues/10890

# Blocking and Needs Owner
- [x] https://github.com/magma/magma/issues/11638
- [x] https://github.com/magma/magma/issues/11897 
- [x] #12355

# Non-Blocking and Needs Owner
- [x] https://github.com/magma/magma/issues/11936 (blocker for coverage collection in CI)
- [x] https://github.com/magma/magma/issues/12181
- [x] https://github.com/magma/magma/issues/12182
- [x] https://github.com/magma/magma/issues/12183
- [x] https://github.com/magma/magma/issues/12184
- [x] https://github.com/magma/magma/issues/12185

### MME dependency Bazel-ification 

Non-blocking because we can let Bazel use system libraries (dynamically linked) - but this approach is not preffered for reasons of dependency consistency challenges across environments, build reproduction, and container size - among other reasons.

- [x] https://github.com/magma/magma/issues/9710 (Not a blocker exactly, this is a nice to have for completeness)
- [x] https://github.com/magma/magma/issues/9728 (small)
- [x] https://github.com/magma/magma/issues/10796 (small)
- [x] https://github.com/magma/magma/issues/10797 (small)
- [x] https://github.com/magma/magma/issues/10800 (small)
- [x] https://github.com/magma/magma/issues/10798 (small)

# Final Clean Up (Once Bazel-ified)
- [x]  https://github.com/magma/magma/issues/11736
- [x]  https://github.com/magma/magma/issues/11760
- [x] https://github.com/magma/magma/issues/11959
- [x] #11767 (small) (@ajahl @vktng  @nstng )
- [x] Migrate code coverage generation in CI agw-workflow
- [x] #12153

## MME dependency cycle refactoring tasks
- [x] #11892

# In Progress
- [x] #12057 (@jheidbrink  @LKreutzer )
- [x] https://github.com/magma/magma/issues/11656 (@electronjoe)

# Completed!
- [x] #12232
- [x] #12233 
- [x] #11861 (hard) (@ajahl @vktng  @nstng )
- [x] https://github.com/magma/magma/issues/11537
- [x] https://github.com/magma/magma/issues/10320
- [x] https://github.com/magma/magma/issues/11532
- [x] https://github.com/magma/magma/issues/11646 (@themarwhal)
- [x] #11881
- [x] #11899 (@electronjoe)
- [x] #11862 (@electronjoe)
- [x] #11950
- [x] https://github.com/magma/magma/issues/11779
- [x] https://github.com/magma/magma/issues/11712 (medium) (@ajahl @LKreutzer)
- [x] https://github.com/magma/magma/issues/9715
- [x] #11860 (small)
- [x] #11898
- [x] #12093
- [x] https://github.com/magma/magma/issues/11591 (hard)
- [x] https://github.com/magma/magma/issues/11660 (medium) (@LKreutzer @ajahl )
- [x] #11984 (@nstng)
- [x] #12103
- [x] #12105
- [x] #12146
- [x] #12147

### MME dependency Bazel-ification
- [x] https://github.com/magma/magma/issues/9730
- [x] https://github.com/magma/magma/issues/10672

### MME dependency cycle refactoring tasks
- [x] https://github.com/magma/magma/issues/9732
- [x] https://github.com/magma/magma/issues/9817
- [x] https://github.com/magma/magma/issues/9819
- [x] https://github.com/magma/magma/issues/9861

### Unit Test Failures
- [x] #12163
- [x] https://github.com/magma/magma/issues/11676
- [x] https://github.com/magma/magma/issues/11823 (@electronjoe)
- [x] https://github.com/magma/magma/issues/11785 (@ardzoht)
- [x] #11841
- [x] #11842
- [x]  https://github.com/magma/magma/issues/11992 (@themarwhal )
- [x] #11951 (@ajahl @LKreutzer)
- [x]  https://github.com/magma/magma/issues/11993 (@themarwhal )
- [x] #11994
- [x] #11983 (@ajahl @LKreutzer )
- [x] https://github.com/magma/magma/issues/11783 (@ajahl @vktng @nstng )
- [x] https://github.com/magma/magma/issues/11678 (@ajahl @vktng @nstng )
- [x] #12061
- [x] https://github.com/magma/magma/issues/11827
- [x] #12102
- [x] https://github.com/magma/magma/issues/12066
- [x] #11955
- [x] #12145
- [x] #12144
- [x] https://github.com/magma/magma/issues/12166
- [x] #12310
- [x] https://github.com/magma/magma/issues/11826 (@Krishnavamsi-wavelabs)

### MME Build + Test Hackathon

The following stack of PRs achieved Bazel build of MME, and a suite of MME unit tests (not all but a good start). We leave the list here as evidence of work accomplished towards this goal.

- [x] #11580
- [x] #11578
- [x] #11554
- [x] #11552
- [x] #11562
- [x] #11556
- [x] #11550
- [x] #11560
- [x] #11564
- [x] #11566
- [x] #11568
- [x] #11558
- [x] #11545
- [x] #11586
- [x] #11571
- [x] #11574
- [x] #11589
- [x] #11593
- [x] #11594
- [x] #11595
- [x] #11596
- [x] #11603
- [x] #11606
- [x] #11611
- [x] #11658
- [x] #11679
- [x] #11585
- [x] #11889

**Comment by themarwhal** [comment]
Current MME unit test status from [this Bazel MME Unit test branch](https://github.com/electronjoe/magma/tree/pr-giant-bazel-mme-rebase).

For running tests with ASAN/LSAN with CMake, apply this https://github.com/magma/magma/pull/11883

| Test                                               | Plain | ASAN  | LSAN  |
| -------------------------------------------------- | ----- | ----- | ----- |
| spgw_task:spgw_procedures_with_injected_state_test |  pass |  pass |  pass |
| spgw_task:spgw_procedures_test                     |  **RESOLVED** |  **RESOLVED** |  **RESOLVED** |
| spgw_task:pgw_pco_test                             |  **RESOLVED** |  **RESOLVED** |  **RESOLVED** |
| sgw_s8_task:sgw_s8_test_attach_proc_test           |  pass |  **RESOLVED** |  pass |
| sgw_s8_task:sgw_s8_recv_grpc_messages_test         |  pass |  pass |  pass |
| sgw_s8_task:sgw_dedicated_bearer_test              |  pass |  **RESOLVED** |  pass |
| s1ap_task:s1ap_state_manager_test                  |  pass |  pass |  pass |
| s1ap_task:s1ap_state_converter_test                |  pass |  pass |  pass |
| s1ap_task:s1ap_mme_handlers_test                   |  pass |  pass |  pass |
| s1ap_task:s1ap_handle_new_association_test         |  pass |  pass |  pass |
| pipelined_client:pipelined_client_test             |  pass |  pass |  pass |
| openflow:openflow_controller_test                  |  pass |  pass |  pass |
| openflow:imsi_encoder_test                         |  pass |  pass |  pass |
| openflow:gtp_app_test                              |  pass |  **RESOLVED** |  pass |
| ngap:ngap_state_converter_test                     |  pass |  pass |  pass |
| ngap:ngap_handle_new_association_test              |  pass |  pass |  pass |
| ngap:ngap_flows_test                               |  pass |  pass |  pass |
| ngap:ngap_encode_decode_test                       |  pass |  pass |  pass |
| nas:nas_converter_test                             |  **RESOLVED** |  **RESOLVED** |  pass |
| n11:n11_smf_service_client_test                    |  pass |  **RESOLVED** |  pass |
| n11:n11_auth_service_client_test                   |  pass |  pass |  pass |
| mme_app_task:sgw_config_test                       |  **RESOLVED** |  **RESOLVED** |  **RESOLVED** |
| mme_app_task:mme_procedures_test                   |  pass |  **FAIL** |  pass |
| mme_app_task:mme_app_nas_encode_decode_test        |  pass |  pass |  pass |
| mme_app_task:mme_app_esm_encode_decode_test        |  pass |  pass |  pass |
| mme_app_task:mme_app_emm_encode_decode_test        |  pass |  pass |  pass |
| mme_app_task:mme_app_config_test                   |  pass |  pass |  pass |
| mme_app_task:eps_quality_of_service_test           |  pass |  pass |  pass |
| mme_app_task:apn_aggregate_maximum_bit_rate_test   |  pass |  pass |  pass |
| lib:lib_bstr_test                                  |  pass |  pass |  pass |
| lib:lib_3gpp_test                                  |  pass |  pass |  pass |
| itti:itti_test                                     |  pass |  pass |  pass |
| gtpv2-c:gtpv2_fteid_test                           |  pass |  pass |  pass |
| amf:amf_stateless_test                             |  pass |  **FAIL** |  pass |

**Comment by electronjoe** [comment]
GH Issue is preventing me from editing the original GH Issue.

Need to add:
- [x] #12155
